kind: pipeline
type: kubernetes
name: default

concurrency:
  limit: 1

node_selector:
  drone/blackufa: true

volumes:
- name: cache
  host:
    path: /data/drone/workspaces/blackufa-legacy
- name: base_repo
  host:
    path: /data/drone/workspaces/blackufa

clone:
  disable: true

trigger:
  branch:
  - master

steps:
- name: chown-cache
  image: alpine
  pull: if-not-exists
  volumes:
  - name: cache
    path: /drone/cached
  commands:
  - chown 1000:1000 /drone/cached

- name: build
  image: thedrhax/buildenv-blackufa
  volumes:
  - name: cache
    path: /drone/cached
  - name: base_repo
    path: /drone/base
  environment:
    SSH_KEY:
      from_secret: ssh_key
    PYTHONUNBUFFERED: 1
  commands:
  - |
    mkdir ~/.ssh
    echo "$SSH_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa

  - cd /drone/cached

  - |
    if [ ! -d .git ]; then
      git clone $DRONE_GIT_SSH_URL .
      git config --local user.email "the.dr.hax@gmail.com"
      git config --local user.name "Drone"

      mkdir -p .git/objects/info
      echo /drone/base/.git/objects > .git/objects/info/alternates
    else
      if [ ! -e .git/objects/info/alternates ]; then
        echo /drone/base/.git/objects > .git/objects/info/alternates
      fi

      git fetch
    fi

    git checkout $DRONE_COMMIT

  - ./bsu venv update
  - ./bsu repo pull --force

  - ./bsu download-chats
  - ./bsu build

  # Do not push chats
  # Chat archives are managed by TheDrHax/BlackSilverUfa
  - './bsu pages commit "Drone: Обновление статичных файлов"'
  - ./bsu pages push _site

  - ./bsu repo prune --optional
  - git gc --prune=now
